src/dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from news.views import word_count_list, bar_graph, ChartData


urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('home/', word_count_list, name='home'),
    path('homebar/', bar_graph, name="bar_graph_url"),
    re_path(r'^api/chart/data/$', ChartData.as_view(), name="api_chart_data"),

]

src/news/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from .views import scrape

app_name = 'news'

urlpatterns = [
    re_path(r'^scrape/$', scrape, name='scrape_url'),
]

src/news/models.py
from django.db import models

from django.conf import settings

# model -- headline(title, url, image)
# model -- userprofile(user, last_scrape) so that we can limit number of scrapes

class Headline(models.Model):
    title = models.CharField(max_length=120)
    image = models.ImageField()
    url = models.TextField()

    def __str__(self):
        return self.title
class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    last_scrape = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return "{}-{}".format(self.user, self.last_scrape)

class WordAndCount(models.Model):
    word = models.CharField(max_length=120)
    count = models.IntegerField()

    def __str__(self):
        return self.word

src/news/views.py
from django.shortcuts import render, redirect
import requests
from bs4 import BeautifulSoup
from collections import Counter
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.probability import FreqDist
from nltk.stem import PorterStemmer
import re
from .models import UserProfile, Headline, WordAndCount

from TurkishStemmer import TurkishStemmer

from rest_framework.views import APIView
from rest_framework.response import Response

class ChartData(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        words = dict()
        for w in WordAndCount.objects.all().order_by('-id')[:10]:
            words[w.word] = w.count
        words = dict(words)
        data = {
            "word": words.keys(),
            "count": words.values(),
        }
        return Response(data)
        
def bar_graph(request):
    return render(request, "news/plotly.html", {})
def word_count_list(request):
    all_words_and_counts = WordAndCount.objects.all().order_by('-id')[:10]
    context = {
        'object_list': all_words_and_counts
    }
    return render(request, "news/home.html", context)

def scrape(request):
    session = requests.Session()
    session.headers = {'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36'}
    url = 'https://www.birgun.net/guncel'
    main_url = 'https://www.birgun.net'
    content = session.get(url, verify=False).content
     
    soup = BeautifulSoup(content, "html.parser")
    first_news = soup.findAll("div", {"class": "aciklamali-haber haber"})
    total_text = ''
    for i in first_news:
        link = i.find('a')
        im_source = i.find('img')['src']
        
        news_detail_url =main_url + link.get('href')
        detail_content = session.get(news_detail_url, verify=False).content
        soup = BeautifulSoup(detail_content,"html.parser")
        paragraphs = soup.find('div', {"class": "body fw"}).findAll('p')
        i = 0
        for p in paragraphs:
            total_text = total_text + p.text + '\n'
    
    words = word_tokenize(total_text)
    stop_words = set(stopwords.words("turkish"))
    my_words = {"bir","Bu", "var", "sonra","yok","olarak","yapılan","değil","göre","tarafından","ardından","geri","ileri","devam","eden"
                        "hatta","bazen","ilgili", "Ben","ben","ama","Bir","olmak","üzere","bin","ton","kota"
    }
    stop_words = stop_words.union(my_words) 
    filtered_words = [w for w in words if not w in stop_words]

    non_punct = re.compile('.*[A-Za-z0-9].*')  # must contain a letter or digit
     
    # ONE LINER FOR THE SAME JOB
    #double_filtered = [w for w in filtered_words if non_punct.match(w)]
    stemmer = TurkishStemmer()

    final_list = []
    for w in filtered_words:
        if non_punct.match(w):
            std = stemmer.stem(w)
            final_list.append(std)
    #print(final_list)
    counts = Counter(final_list)

    
    fdist = FreqDist(final_list)
    common_ones = fdist.most_common(10)
    for i, (w,c) in enumerate(common_ones):
        new_word_and_count = WordAndCount()
        new_word_and_count.word = w
        new_word_and_count.count = c
        new_word_and_count.save()

    
    
    return redirect('/home/')

src/news/templates/news/home.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
<!-- Latest compiled and minified CSS -->
<!--
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity=
	"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
-->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity=
	"sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
</head>
<body>
    <div class="jumbotron">
        <h1>Welcome to Dashboard</h1>
            <form method="POST" action="{% url 'news:scrape_url' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Get the News</button>
            </form>
        
    </div>

    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">WORD</th>
            <th scope="col">COUNT</th>
          </tr>
        </thead>
        <tbody>
                {% for object in object_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ object.word }}</td>
                    <td>{{ object.count }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    <!--
    <div class="container">
        <div class="row">
            <div class="col-sm-3 text-center">
                {% for object in object_list %}
                <div class="card text-center">
                    <h5 class="card-title">"{{ object.word }}" :{{ object.count }}</h5>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
-->




</body>
</html>

src/news/templates/news/plotly.html
<!DOCTYPE html>
<html>
<head>
       

<title></title>
</head>
<body>
        
    <div class="row">
        <div id="word-count" style="width:1400px; height:600;" ></div>
    </div>

    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
	<script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>


    <script type="text/javascript">
        $(document).ready(function(){
            var endpoint = '/api/chart/data'
            var wordName = wordCount = []
        $.ajax({
            method: "GET",
            url: endpoint,
            success: function(data){
                wordName = data.word
                wordCount = data.count
                wordChart()
            },
            error: function(error_data){
                console.log("error")
            },

        })

        function wordChart(){
            var data = [{
                x: wordName,
                y: wordCount,
                type: 'bar',
                orientation: 'v',
                marker: {
                    color: '#23b7e5',
                }, 
            }];
            var layout = {
                title: "Top Words Used in Today's News",
                margin: {l:200},
            };
        Plotly.newPlot('word-count',data, layout);
        }

        })
    </script>
</body>
</html>